// <auto-generated />
namespace NewAPIProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class contactus10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contactus10));
        
        string IMigrationMetadata.Id
        {
            get { return "202004101704322_contact-us-10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
